[package]
name = "walker"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_turborand.workspace = true
